### ISSUE TITLE
[Enhancement] Add Transifex Service to translate to other languages.

### ISSUE THREAD

**Issue by LordBat** [karhel/glpi-dporegister#10]
It will be great to translate the plugin in transifex. I can translate on es_AR  (Spanish-Argentina).

Thanks!

**Comment by LordBat** [comment]
Hi,
No, i can't find it. Maybe you should add it in the main description to get in to it.

**Comment by karhel** [comment]
Hi, 
Thank you for the translation !
I will add it on the README file.
