### ISSUE TITLE
[feature] LawfulBasis : extend with local regulation

### ISSUE THREAD

**Issue by ladenree76000** [karhel/glpi-dporegister#15]
Plugin allows to set law full basis according to GRDP art.6 ( hardcoded)

Some other local regulation could also apply.
I think it would be usefull to have a managed list for local regulations.

(this means new class lawfulbasis, new table glpi_plugin_dporegister_lawfulbasis with ID,name and description, new dropdown,new profile rights...)

**Comment by karhel** [comment]
Hi,

You can now declare specifics regulations in v1.3
