### ISSUE TITLE
[1.2]+glpi 9.3.1  : php error

### ISSUE THREAD

**Issue by ladenree76000** [karhel/glpi-dporegister#18]
HI,
If found this error in glpi log file.
only when DPOregister is activated.

2018-10-16 11:58:26 [4883@MyServer-test]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:323                          Toolbox::deprecated()
  inc/db.function.php:178                            DbUtils->countElementsInTable()
  plugins/dporegister/inc/profile.class.php:266      countElementsInTable()
  inc/plugin.class.php:1284                          PluginDporegisterProfile::initProfile()
  inc/session.class.php:436                          Plugin::doHook()
  inc/session.class.php:151                          Session::changeProfile()
  inc/auth.class.php:840                             Session::init()
  front/login.php:84                                 Auth->login()

PHP 7.0.32-0 ubuntu0.16.04.1 mariadb  10.0.36

**Comment by karhel** [comment]
Hi,

Only warnings, no worry
I will try to fix that on one of the next versions.

**Comment by karhel** [comment]
Deprecated functions removed in v1.4
