### ISSUE TITLE
[1.1] bad folder name when install

### ISSUE THREAD

**Issue by ladenree76000** [karhel/glpi-dporegister#9]
when extracting archive into glpi/plugin folder name should be "dporegister" instead "glpi-dporegister-1.1"

**Comment by karhel** [comment]
Hi,

Is not that how it's supposed to work? the folder's name corresponds on the repo name

All the plugins that I've downloaded give to me the same result, I have to rename the folder.
I tried on your plugin (formcreator) and it's the same thing, the extraction give to me a folder named "formcreator-2.5.2"

Maybe I don't understant your asking ...

**Comment by ladenree76000** [comment]
OK you're right, i downloaded source code file. I thought it  was installation package. I should have read it better.

I'm not the author from formrcreator plugin  :-(

**Comment by karhel** [comment]
No problem, I added to the current release an installation package.
